// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(SchoolDbContext))]
    [Migration("20250506042306_MigracionInicial")]
    partial class MigracionInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Core.Entities.RegistredUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RegistredUsers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "usuariouno@school.com",
                            IsActive = true,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 3,
                            Email = "usuariodos@school.com",
                            IsActive = false,
                            Name = "Usuario"
                        },
                        new
                        {
                            Id = 4,
                            Email = "usuariotres@school.com",
                            IsActive = true,
                            Name = "Usuario"
                        },
                        new
                        {
                            Id = 8,
                            Email = "usuariocuatro@school.com",
                            IsActive = false,
                            Name = "Invitado"
                        },
                        new
                        {
                            Id = 9,
                            Email = "usuariocinco@school.com",
                            IsActive = true,
                            Name = "Invitado"
                        },
                        new
                        {
                            Id = 10,
                            Email = "usuarioseis@school.com",
                            IsActive = false,
                            Name = "Invitado"
                        },
                        new
                        {
                            Id = 11,
                            Email = "usuariosiete@school.com",
                            IsActive = true,
                            Name = "Invitado"
                        });
                });

            modelBuilder.Entity("Core.Entities.SchoolClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Period")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("TeacherId");

                    b.ToTable("SchoolClasses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Period = 0,
                            StudentId = 8,
                            TeacherId = 3,
                            Time = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Period = 0,
                            StudentId = 10,
                            TeacherId = 3,
                            Time = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Period = 0,
                            StudentId = 9,
                            TeacherId = 4,
                            Time = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            Period = 0,
                            StudentId = 11,
                            TeacherId = 4,
                            Time = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Core.Entities.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TutorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TutorId");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 8,
                            Age = 24,
                            Name = "Ricardo Parra",
                            TutorId = 1
                        },
                        new
                        {
                            Id = 9,
                            Age = 30,
                            Name = "Maria Caro"
                        },
                        new
                        {
                            Id = 10,
                            Age = 28,
                            Name = "Jose Botella"
                        },
                        new
                        {
                            Id = 11,
                            Age = 34,
                            Name = "Marcos Aguilar",
                            TutorId = 2
                        });
                });

            modelBuilder.Entity("Core.Entities.Teacher", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Speciality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Teachers");

                    b.HasData(
                        new
                        {
                            Id = 3,
                            Name = "Dr. Fernandez",
                            Speciality = "Matematica"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Prof. Gomez",
                            Speciality = "Lengua"
                        });
                });

            modelBuilder.Entity("Core.Entities.Tutor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tutors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Madre",
                            Name = "Maria Parra",
                            Phone = "+3469850245"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Tio",
                            Name = "Pedro Caro",
                            Phone = "+3463750285"
                        });
                });

            modelBuilder.Entity("Core.Entities.UserProfile", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("AvatarUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NickName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserProfiles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AvatarUrl = "https://ejemplo.com/avatar1.png",
                            NickName = "Bathman01"
                        },
                        new
                        {
                            Id = 3,
                            AvatarUrl = "https://ejemplo.com/avatar2.png",
                            NickName = "Simpson01"
                        },
                        new
                        {
                            Id = 4,
                            AvatarUrl = "https://ejemplo.com/avatar3.png",
                            NickName = "WonderWoman2"
                        },
                        new
                        {
                            Id = 8,
                            AvatarUrl = "https://ejemplo.com/avatar4.png",
                            NickName = "Catwoman01"
                        },
                        new
                        {
                            Id = 9,
                            AvatarUrl = "https://ejemplo.com/avatar5.png",
                            NickName = "Phinias&Frebs"
                        },
                        new
                        {
                            Id = 10,
                            AvatarUrl = "https://ejemplo.com/avatar6.png",
                            NickName = "TomyYDaly"
                        },
                        new
                        {
                            Id = 11,
                            AvatarUrl = "https://ejemplo.com/avatar7.png",
                            NickName = "Harrypotter"
                        });
                });

            modelBuilder.Entity("Core.Entities.SchoolClass", b =>
                {
                    b.HasOne("Core.Entities.Student", "Student")
                        .WithMany("SchoolClasses")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.Teacher", "Teacher")
                        .WithMany("SchoolClasses")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("Core.Entities.Student", b =>
                {
                    b.HasOne("Core.Entities.Tutor", "Tutor")
                        .WithMany("Students")
                        .HasForeignKey("TutorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("Core.Entities.UserProfile", b =>
                {
                    b.HasOne("Core.Entities.RegistredUser", "RegistredUser")
                        .WithOne("Profile")
                        .HasForeignKey("Core.Entities.UserProfile", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RegistredUser");
                });

            modelBuilder.Entity("Core.Entities.RegistredUser", b =>
                {
                    b.Navigation("Profile");
                });

            modelBuilder.Entity("Core.Entities.Student", b =>
                {
                    b.Navigation("SchoolClasses");
                });

            modelBuilder.Entity("Core.Entities.Teacher", b =>
                {
                    b.Navigation("SchoolClasses");
                });

            modelBuilder.Entity("Core.Entities.Tutor", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
